import makeRequest, { endPoints } from './constants';

const createSalesReceipt = ({
  companyID,
  documentType,
  serie,
  seriesNumber,
  accountingParty,
  company,
  documentDate,
  postingDate,
  currency,
  exchangeRate,
  checkEndorsed,
  isPaymentMethodCheck,
  allowanceChargeAmount,
  grossValue,
  payableAmount,
  wTaxTotal,
  taxTotal,
  taxExclusiveAmount,
  receiptLines,
}) => makeRequest({
  method: 'POST',
  endPoint: endPoints.receipts,
  data: {
    documentType,
    serie,
    seriesNumber,
    accountingParty,
    company,
    documentDate,
    postingDate,
    currency,
    exchangeRate,
    checkEndorsed,
    isPaymentMethodCheck,
    allowanceChargeAmount,
    grossValue,
    payableAmount,
    wTaxTotal,
    taxTotal,
    taxExclusiveAmount,
    receiptLines,
  },
  companyID,
});

export default createSalesReceipt;
