#!/usr/bin/env bash

npm run adonis seed -- --files='UserSeeder.js, CompanySeeder.js, ActionSeeder.js, TriggerSeeder.js' && npm run adonis seed -- --files='ProcessTypeSeeder.js, StepSeeder.js, ProductSeeder.js, EntitySeeder.js' && npm run adonis seed -- --files='ProcessSeeder.js, ProcessedFileSeeder.js, OrderCorrespondenceSeeder.js'
